# Generated by Django 2.2 on 2023-07-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='hobby_image',
            field=models.CharField(default='https://clipart-library.com/img/48366.jpg', max_length=2000),
        ),
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.CharField(default='https://www.pngitem.com/pimgs/m/302-3024031_projects-icon-png-skills-icon-for-resume-png.png', max_length=2000),
        ),
    ]
